version: '3.8'

services:
  src:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: store
      MYSQL_USER: user
      MYSQL_PASSWORD: 
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
